### ISSUE TITLE
Request- ColorFlow compatibility 

### ISSUE THREAD

**Issue by ahanank** [CreatureSurvive/Fabric#4]
Would be nice to have colors change dynamically with ColorFlow :)

**Comment by CreatureSurvive** [comment]
I should hopefully have this working in todays update, Im working on it right now.

**Comment by CreatureSurvive** [comment]
Just finished adding support for this. expect an update later today.

**Comment by ahanank** [comment]
Amazing! Thank you :)

**Comment by ahanank** [comment]
Also, just realized that ‘full size mode’ on ColorFlow doesn’t hide the text from Fabric. Is that normal behavior?
