### ISSUE TITLE
Custom Color Not Display After Respring

### ISSUE THREAD

**Issue by jgeo1** [CreatureSurvive/Fabric#5]
iPhone 6s Plus 12.1.1 u0; Must toggle a setting in Fabric after every respring while pulling down NC for set custom color to take effect, otherwise it always reverts to plain white on LS and Today’s View. If I don’t pull down NC after toggling a setting it still won’t fix the set color back. In other words, this is how I get my set colors back after respring. Open Fabric settings, open top line and toggle from lower or upper case, pull NC down, and the set color changes for that specific line. Afterwards, I repeat this for the next 2 lines (middle,bottom).

**Comment by jgeo1** [comment]
Everything I had installed that affected my LS and NC/Today’s View (to my knowledge) I had removed trying to see if there was a conflict. 
I removed: LittleXS, Notifica, Chromahomebar, and Customlockscreenduration. Here’s a shoddy video of what I tried explaining above. 

https://www.dropbox.com/s/89mhp1uiszwunmb/IMG_2093.mov?dl=0

**Comment by CreatureSurvive** [comment]
@jgeo1 thanks for the detailed report, I was able to reproduce this issue on my device and have managed to get it fixed in the update I'm working on. I'm hoping to have it released by the end of today.

**Comment by jgeo1** [comment]
Thanks for taking the time to look into this issue and for your time and hard work. Also, I’m so excited about the new features you plan to implement into Fabric!
