### ISSUE TITLE
Automatic Coloring with tweak like Freshwall not working properly

### ISSUE THREAD

**Issue by davis12361** [CreatureSurvive/Fabric#6]
Hi, I’m using iPhoneX with iOS 12.1. The color won’t change simultaneously when the wallpaper changed. Also, can you please make an option to let the color lighter than the wallpaper? It’s hard to tell with the color so close. Thanks for your hard work!

**Comment by CreatureSurvive** [comment]
@davis12361 I'll have to purchase FreshWall before I can debug this issue, I will see about refining the logic for detecting wallpaper changes though to see if I can fix this without purchasing. I've also added better legibility settings in the update I'm currently working on, as well as adjustment settings so you can tweak the colors for better visibility. I'll hopefully have this update out later today.
